name: nebulasilva_production

networks:
  app:
    name: nebulasilva_app

services:
  app:
    container_name: nebulasilva_app
    restart: always
    build:
      context: ../..
      dockerfile: docker/production/Dockerfile
    networks:
      - app