on:
  workflow_dispatch:

jobs:
  app:
    runs-on: [self-hosted, production]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker compose -f docker/production/docker-compose.yml build

      - name: Run Docker Compose
        run: |
          docker compose -f docker/production/docker-compose.yml up -d --remove-orphans