on:
  workflow_dispatch:

jobs:
  app:
    runs-on: [self-hosted, production]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker compose -f docker/production/docker-compose.yml build

      - name: Run Docker Compose
        run: |
          docker compose -f docker/production/docker-compose.yml up -d --remove-orphans

      - name: Wait 10sec
        run: |
          sleep 10

      - name: Ensure container are running (no exit code)
        run: |
          OUTPUT=$(docker compose -f docker/production/docker-compose.yml ps)
          echo "$OUTPUT"

          if echo "$OUTPUT" | grep -E "Exit [^0]"; then
            echo "❌ One or more containers exited with a non-zero code."
            exit 1
          else
            echo "✅ All containers are running or exited cleanly."
          fi

      - name: Notify deployment error
        if: failure()
        run: |
          docker compose -f docker/production/docker-compose.yml logs --tail 100